### ISSUE TITLE
Resolution issues using QtInteractor

### ISSUE THREAD

**Issue by JBum21** [pyvista/pyvistaqt#101] opened 2021-04-29 21:47 UTC
As stated above, I am having some odd resolution issues when adding meshes to a Qtinteractor.

Below you can see a screenshot demonstrating the poor resolution of the object when zoomed out (Most obvious when comparing "arc_length" resolution to the 3rd screenshot).
<img width="1566" alt="Screen Shot 2021-04-29 at 5 18 56 PM" src="https://user-images.githubusercontent.com/70919881/116622407-a785c780-a912-11eb-8d14-88132ac55a14.png">

In contrast, when zoomed in, the lines become more smooth, but the resolution of "arc length" stays the same...
<img width="1566" alt="Screen Shot 2021-04-29 at 5 25 04 PM" src="https://user-images.githubusercontent.com/70919881/116622439-b40a2000-a912-11eb-8293-41b8b1ef2ffd.png">

This might have something to do with my MacBook Pro monitor, however, because observing the mesh on my external monitor produces a smoother image (and appropriate resolution text for the scalar bar). Loading here doesn't solve anything, as the resolutions don't appear different when when taking a screenshot.

These issues are not present when using the pure PyVista.Plotter() from the command line:
<img width="1566" alt="Screen Shot 2021-04-29 at 5 38 12 PM" src="https://user-images.githubusercontent.com/70919881/116622547-e0be3780-a912-11eb-8aef-4161aa9f6afb.png">

I am creating the plotter using: 
` self.plotter = QtInteractor(multi_samples=8,line_smoothing=True, point_smoothing=True, polygon_smoothing=True) `
and add meshes to the plotter using:
`self.plotter.add_mesh(examplemesh)`

Please let me know if there is anything I can do to improve/solve this issue. Any help would be appreciated.

Thanks

**Comment by JBum21** [comment] 2021-05-03 13:44
It seems like this is an issue with PyQt versions 5.14 >=. See gitlab issue [#17953](https://gitlab.kitware.com/vtk/vtk/-/issues/17953#note_949062)

**Comment by GuillaumeFavelier** [comment] 2021-05-07 08:31
Closing as a duplicate of https://github.com/pyvista/pyvistaqt/issues/20

**Closed by GuillaumeFavelier** 2021-05-07 08:31 UTC
