### ISSUE TITLE
Windows fatal exception

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvistaqt#13] opened 2020-06-06 16:36 UTC
Received an email:

> Dear PyVista Team,
>
> I would like to report a supposed bug: the QtInteractor is producing a Windows fatal exception (code 0x8001010d) when the Qt window is moved or clicked. I am running the first example code in https://qtdocs.pyvista.org/qt_plotting.html. See the print screen below, please. Congratulations on the PyVista project.

![image](https://user-images.githubusercontent.com/22067021/83949451-dde5c000-a7f1-11ea-810d-798c60765f6b.png)

**Comment by akaszynski** [comment] 2020-06-07 00:51
@banesullivan, could they please send out a scooby report?

**Comment by rodrigomologni** [comment] 2020-06-09 01:35
Hi, @akaszynski,

I'm Rodrigo. I sent the email to @banesullivan. See below the scooby report.

Thank you!

```
--------------------------------------------------------------------------------
  Date: Mon Jun 08 22:30:36 2020 Hora oficial do Brasil

                OS : Windows
            CPU(s) : 4
           Machine : AMD64
      Architecture : 64bit
       Environment : Python

  Python 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64
  bit (AMD64)]

           pyvista : 0.25.2
               vtk : 9.0.0
             PyQt5 : 5.14.2
         pyvistaqt : 0.1.0
             numpy : 1.17.3
             scipy : 1.4.1
        matplotlib : 3.2.1
            scooby : 0.5.2
--------------------------------------------------------------------------------
```

**Comment by akaszynski** [comment] 2020-06-09 05:33
Issue is likely with VTK 9.0.  Can you please see if it still occurs with vtk==8.1.2?  A simple pip install should do it:
```
pip install vtk==8.1.2
```

**Comment by rodrigomologni** [comment] 2020-06-09 12:51
I uninstalled the VTK 9.0.0 and installed the VTK 8.1.2 as requested, but the error continues:

```
Windows fatal exception: code 0x8001010d

Current thread 0x0000095c (most recent call first):
  File "D:\Users\Rodrigo\Desktop\demo.pyw", line 52 in <module>
```

Line 52:

`sys.exit(app.exec_())`

**Comment by akaszynski** [comment] 2020-06-09 15:10
@rodrigomologni, can you please post the entire source here so I can reproduce this locally?

Glad to know it's not a vtk problem...

**Comment by rodrigomologni** [comment] 2020-06-09 15:17
@akaszynski the source is the **Example PyQt5 PyVista QtInteractor** available at https://qtdocs.pyvista.org/qt_plotting.html.

**Comment by akaszynski** [comment] 2020-06-09 15:18
Thanks!

**Comment by GuillaumeFavelier** [comment] 2020-07-16 09:46
Do you still encounter this issue @rodrigomologni ? Many things have changed since then (new release `vtk 9.0.1`, inheritance change in #25, ...)

**Comment by rodrigomologni** [comment] 2020-07-16 11:58
Hi @GuillaumeFavelier! Yes, the problem still occur.

```
--------------------------------------------------------------------------------
  Date: Thu Jul 16 08:54:54 2020 Hora oficial do Brasil

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
       Environment : Python

  Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64
  bit (AMD64)]

           pyvista : 0.25.3
               vtk : 9.0.1
             PyQt5 : 5.15.0
         pyvistaqt : 0.1.1
             numpy : 1.19.0
        matplotlib : 3.2.2
            scooby : 0.5.5
--------------------------------------------------------------------------------
```

**Comment by GuillaumeFavelier** [comment] 2020-07-16 13:49
Thanks for trying again. I will give it a try on my Windows and see if I can reproduce too :+1:

**Comment by rodrigomologni** [comment] 2020-07-16 13:54
@GuillaumeFavelier You're welcome! I can test here again if you need to. :v:

**Comment by rodrigomologni** [comment] 2020-09-30 18:19
Hi @GuillaumeFavelier! Were you able to identify the source of the error? I'm curious and anxious for the solution. 😅

**Comment by adamgranthendry** [comment] 2021-08-04 23:24
@rodrigomologni Are you able to upgrade to `python 3.8`? I only ask because it might help if you are able to upgrade. I am unable to reproduce your results on Windows 10 with Python 3.8.

**Comment by rodrigomologni** [comment] 2021-08-05 12:54
Hi @adamgranthendry! I also couldn't reproduce the error, even in Python 3.7. However, I'm using the current versions of Python 3.7, PyVista, VTK, PyQt5 etc. Thank you!

```
--------------------------------------------------------------------------------
  Date: Thu Aug 05 09:43:46 2021 Hora oficial do Brasil

                OS : Windows
            CPU(s) : 8
           Machine : AMD64
      Architecture : 64bit
       Environment : Python

  Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64
  bit (AMD64)]

           pyvista : 0.31.3
               vtk : 9.0.3
             PyQt5 : 5.15.4
         pyvistaqt : 0.5.0
             numpy : 1.21.1
        matplotlib : 3.4.2
            scooby : 0.5.7
--------------------------------------------------------------------------------
```

**Comment by adamgranthendry** [comment] 2021-08-05 15:42
@rodrigomologni That's great news! So, do I understand you correctly, is your problem solved now?

**Comment by rodrigomologni** [comment] 2021-08-05 15:45
Yes! We can close this issue. :wink:

**Closed by rodrigomologni** 2021-08-05 15:45 UTC
